# This is a basic workflow to help you get started with Actions we do
#test this workflow
name: Build & Test

on:
  push:
    paths:
    - 'apis/poi/**'

defaults:
  run:
    working-directory: ./apis/poi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
  
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy image to acr
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYHACKAZURE }}
      - run: |
          docker build apis/poi/web/Dockerfile -t openhackvtk50d57acr.azurecr.io/poi:${{ github.sha }}
          docker push openhackvtk50d57acr.azurecr.io/poi:${{ github.sha }}  
